version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    allowed:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "tokio"
        versions: ["1.0.0"]
    open-pull-requests-limit: 5
    groups:
      infrastructure:
        patterns:
          - "tokio"
          - "actix-web"
          - "serde"
          - "anyhow"
          - "thiserror"
      utilities:
        patterns:
          - "reqwest"
          - "tracing"
          - "redis"
          - "prometheus"
          - "chrono"
      machine-learning:
        patterns:
          - "linfa*"
          - "ndarray*"
          - "smartcore"
          - "statrs"
          - "hyperopt"
