max_width = 100
edition = "2021"
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Max"
fn_args_layout = "Tall"
merge_derives = true
reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
error_on_line_overflow = true
error_on_unformatted = true
version = "Two"
