
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: your-docker-registry/frontend:latest
          ports:
            - containerPort: 8081
          resources:
            limits:
              nvidia.com/gpu: 0
---
