apiVersion: v1
kind: Service
metadata:
  name: personalization-engine
spec:
  selector:
    app: personalization-engine
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: NodePort
