
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  labels:
    app: ai-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
        - name: ai-chatbot
          image: your-docker-registry/ai-chatbot:latest
          ports:
            - containerPort: 8083
          resources:
            limits:
              nvidia.com/gpu: 1
---
