apiVersion: apps/v1
kind: Deployment
metadata:
  name: cybersecurity-ai
  labels:
    app: cybersecurity-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cybersecurity-ai
  template:
    metadata:
      labels:
        app: cybersecurity-ai
    spec:
      containers:
        - name: cybersecurity-ai
          image: your-docker-registry/cybersecurity-ai:latest
          ports:
            - containerPort: 8090
          resources:
            limits:
              nvidia.com/gpu: 1
