apiVersion: v1
kind: Service
metadata:
  name: predictive-analytics
spec:
  selector:
    app: predictive-analytics
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: NodePort
---
