apiVersion: v1
kind: Service
metadata:
  name: rust-anomaly-detector
spec:
  selector:
    app: rust-anomaly-detector
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: NodePort
