[package]
name = "python_service"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common", features = [
    "serialization",
    "async_runtime",
    "error_handling",
    "web_framework",
    "logging",
    "utils",
] }

# Add any crate-specific dependencies below
