name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lld

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Security Checks
        run: |
          cargo install cargo-audit || echo "cargo-audit is already installed"
          cargo audit
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Test Common Library
        run: |
          cd crates/common
          cargo test --verbose
          cd ../..

      - name: Test Core Services
        run: |
          # Test AI Chatbot
          cd crates/ai_chatbot
          cargo test --verbose
          cd ../..
          
          # Test Predictive Analytics
          cd crates/predictive_analytics
          cargo test --verbose
          cd ../..

      - name: Test Dependent Services
        run: |
          # Test Personalization Engine
          cd crates/personalization_engine
          cargo test --verbose
          cd ../..
          
          # Test AutoML
          cd crates/automl
          cargo test --verbose
          cd ../..

      - name: Integration Tests
        run: cargo test --test integration_tests --features=integration
