
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Install lld
        run: sudo apt-get update && sudo apt-get install -y lld
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Check SECURITY.md
        run: |
          if [ ! -f SECURITY.md ]; then
            echo "ERROR: SECURITY.md is missing. Please add it to the repository."
            exit 1
          fi

      - name: Audit Dependencies
        run: |
          cargo install cargo-audit || echo "cargo-audit is already installed"
          cargo audit

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Run Tests
        run: cargo test --verbose
