name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Release
        run: cargo build --release --all-features
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 